# Generated by Django 5.2.1 on 2025-05-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address1',
            new_name='shiping_address1',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address2',
            new_name='shiping_city',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county',
            new_name='shiping_county',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='email',
            new_name='shiping_email',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='full_name',
            new_name='shiping_full_name',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='old_cart',
            new_name='shiping_old_cart',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='shiping_state',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone',
            new_name='shiping_zipcode',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shiping_address2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
