# Generated by Django 5.2.1 on 2025-09-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'در حال انتظار'), ('Processing', 'در حال پردازش'), ('Shipped', 'ارسال شده'), ('Delivered', 'تحویل داده شده')], default='Pending', max_length=50),
        ),
    ]
