# Generated by Django 5.2.1 on 2025-09-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Addresses'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_county',
            new_name='shipping_country',
        ),
    ]
